use_frameworks!

platform :ios, '8.0'

target 'afShareSDKManage_Example' do
  pod 'afShareSDKManage', :path => '../'

  target 'afShareSDKManage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
